
APP := orbit
VERSION := 0.6

SRCS += orbit.c

FONTS := \
	fonts/roboto.ttf:22 \
	fonts/roboto.ttf:14 \

IMAGES := \
	images/menu_icon.png \
	images/face.png \
	images/hour_planet.png:white \
	images/hour_planet.png:black \
	images/minute_planet.png:white \
	images/minute_planet.png:black \

include ../Makefile.pebble
