
APP := orbit

SRCS += orbit.c

FONTS := \
	fonts/roboto.ttf:22 \
	fonts/roboto.ttf:14 \

IMAGES := \
	images/menu_icon.png \
	images/hour_ring.png:white \
	images/hour_ring.png:black \
	images/minute_ring.png:white \
	images/minute_ring.png:black \

include ../Makefile.pebble
